Website/auth.py
from Website import views
from flask import Blueprint, render_template, request, flash, redirect, url_for, session
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db, mail
from flask_login import login_user, login_required, logout_user, current_user
from flask_mail import Mail, Message


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        remember = True if request.form.get('remember') else False
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=remember)                
                return redirect(url_for('views.index'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


    
@auth.route('/signup', methods=['GET','POST'])
def signup(): 
    if request.method == 'POST':
        email = request.form.get('email')
        name = request.form.get('name')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database
       
        if user: # if a user is found, we want to redirect back to signup page so user can try again
            flash('This user already exists',category='error')
            
        elif len(email) < 10:
            flash('Email must be greater than 10 characters.', category='error')
           
        elif len(name) < 3:
            flash('Userame must be greater than 3 character.', category='error')
           
        elif len(password) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            # create a new user with the form data. Hash the password so the plaintext version isn't saved.
            new_user = User(email=email, name=name, password=generate_password_hash(password, method='sha256'),description='',market_products='',users_follow_me='')
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)           
            flash('Account created!', category='success')
            return redirect(url_for('views.index'))
               
    return render_template('signup.html',user=current_user)


@auth.route('/')
@login_required
def logout():
    logout_user()
    return render_template("login.html",user=None)

Website/templates/about.html
{% extends "base.html"%} {% block title %}BuyOrSell{% endblock %}
{% block content %}
  <div class="hero-body is-primary" type=variable value=blue>
    <div  class="container has-text-centered">
  <h1 class="title">
    Welcom {{user.name}}!!!
  </h1>  
  <br>
  <h2 class="subtitle">
   BuyOrSell is a free website made for all people that wish make business with auctions, salles,  or shopping products.
   We count with {{count}} users and {{products_number}} products. And this numbers does't stop growing up.
  </h2>

  <a>
  If you want report one problem or advertise something with more focus please contact : "buy0rs3ll@gmail.com".</a>
  </div>
  </div>
{% endblock %}

Website/templates/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <title>{% block title %}BuyOrSell{% endblock %}</title>      
      <link type="text/javascript" href="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
      <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
      <link
         rel="stylesheet"
         href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
         integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
         crossorigin="anonymous"/>      
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
      <script type="text/javascript" src="{{ url_for('static', filename='index.js') }}"></script>
   </head>
   <body>
      <section class="hero is-sucess is-fullheight" style="background-color:#eff1eb;">
         <div class="hero-head" style="position:fixed; width:100%; opacity:100%; z-index:1;">
            <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="navbar">
               <div class="container">
                  <div id="navbarMenuHeroA" class="navbar-menu">
                     <div class="navbar-end">
                        <a class="navbar-brand" href="{{ url_for('views.index')}}">                       
                        <img  id="logo" src="/static/img/logo1.png/" alt="">
                        </a>                                            
                        {% if user.is_authenticated %}                                
                        <a href="{{ url_for('auth.logout') }}" class="navbar-item" alt="Log out">
                        <i class="fa fa-sign-out fa-fw" aria-hidden="true"></i> &nbsp;Logout
                        </a>
                        <li class="navbar-item dropdown">
                           <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           <i class="fa fa-cog"></i>&nbsp;Settings
                           </a>
                           <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{{ url_for(('views.profile'),id=user.id)}}">
                              <i class="fa fa-user fa-fw" aria-hidden="true"></i> &nbsp;{{user.name}}
                              </a>
                              <a class="dropdown-item" href="{{ url_for('views.buy') }}">
                              <i class="fa fa-shopping-cart" aria-hidden="true"></i> &nbsp;Buy
                              </a>
                              <a class="dropdown-item" href="{{ url_for('views.sell') }}">
                              <i class="fa fa-shopping-cart  fa-flip-horizontal" aria-hidden="true"></i> &nbsp;Sell
                              </a>
                              <a class="dropdown-item" href="{{ url_for('views.auctions') }}">
                              <i class="fa fa-gavel" aria-hidden="true"></i> &nbsp;Auctions
                              </a>
                              <a class="dropdown-item"href="{{ url_for('views.favorites') }}">
                              <i class="fa fa-bookmark-o" aria-hidden="true"></i> &nbsp;Favorites
                              </a>
                              <a class="dropdown-item"href="{{ url_for('views.about') }}">
                              <i class="fa fa-home fa-fw" aria-hidden="true"></i> &nbsp;About
                              </a>                              
                              <div class="dropdown-divider"></div>
                              <div class="dropdown-item" style="background-color:white;">
                              <a class="notification"href="#">
                              {% if user.notification>=1%} 
                                 <span class="badge">{{user.notification}}</span>&nbsp;
                              {%endif%}                          
                              <i class="fa fa-bell-o fa-fw" aria-hidden="true"></i>&nbsp;Notifications                             
                              </a>
                              </div>
                           </div>
                        </li>
                        {%else%}                                                         
                        <a href="{{ url_for('auth.login') }}" class="navbar-item" alt="Login">
                        <i class="fa fa-sign-in fa-fw" aria-hidden="true"></i> &nbsp; Login
                        </a>
                        <a  href="{{ url_for('auth.signup') }}" class="navbar-item" alt="Sign up">
                        <i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> &nbsp;Sign Up
                        </a>
                        {%endif%}                          
                     </div>
                  </div>
               </div>
            </nav>
            {% with messages = get_flashed_messages(with_categories=true) %} 
            {% if messages %} 
            {% for category, message in messages %} 
            {% if category==sucess %}
            <div class="alert alert-success alter-dismissable fade show" role="alert">
               {{ message }}
               <button type="button" class="btn-close" data-dismiss="alert">
               <span aria-hidden="true">&times;</span>
               </button>
            </div>
            {% endif %}{% endfor %}{%endif %}{% endwith %}
         </div>
         {% block content %}{% endblock %}
         </section>
      <script
         src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
         integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
         crossorigin="anonymous"
         ></script>
      <script
         src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
         integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
         crossorigin="anonymous"
         ></script>
      <script
         src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
         integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
         crossorigin="anonymous"
         ></script>
      <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
   </body>
</html>

Website/templates/buy.html
{% extends "base.html"%} {% block title %}Buy{% endblock %}
{% block content %}
<div id="body1" class="container-fluid text-center" type=variable value=blue>
 <div class="hero is-sucess d-flex align-items-center justify-content-center">
      <tr>
         <td>
            <br>                                     
            <div  class="row content d-flex align-items-center justify-content-center" style="height:auto;">
            <div class="box" id="caixaindexpage">
             {% with messages = get_flashed_messages(with_categories=true) %} 
                    {% if messages %} 
                        {% for category, message in messages %} 
                            {% if category =='error' %}
                                <div class="alert alert-danger alter-dismissable fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}{% endfor %}{%endif %}{% endwith %}
                <form method="POST" action="/BuyOrSell/buy"  enctype="multipart/form-data">
                       <ul id="formLabels" style="list-style: none;">
                            <h3 id="title">What are you looking for?</h3>
                            <br>
                            <li>
                                <p style="tabe-size:4;">&emsp;&emsp;Here you can indicate information about the product you want to purchase. Fill in all fields so sellers can accurately understand what you are looking for. Also leave your contact information so that you can communicate with potential sellers. If you just want to announce something, contact is optional. Incorporate a good number of keywords in the description. These made your advertising more accessible.</p>
                            </li>
                            <br>
                            <li>
                                <label id="labels"for="name" class="input-group">
                                <span>Product name</span>
                                </label>                    
                                <input class="input-group" type="text" name="name" style="width:29.1%"placeholder=" Product name">
                            </li>
                            <br>                        
                            <li>
                            <label id="labels"for="description" class="input-group">
                                <span>Price around:</span>&nbsp;&nbsp;&nbsp;
                                <input type="number" required name="price" min="0" value="0" step="0.025">
                            </label>
                            
                            </li>
                           
                            <li>
                                <label id="labels"for="category" class="input-group">
                                <span>What is your product category</span>&nbsp;&nbsp;&nbsp;
                                                                        
                                <select id="select" name="productTypes">
                                   <option value="Accessories">Accessories</option>
                                    <option value="Animals">Animals</option>
                                    <option value="Colections">Colections</option>
                                    <option value="Out side">Out side</option>
                                    <option value="For Home">For Home</option>
                                    <option value="Others">Others</option>
                                    <option value="Clothes">Clothes</option>
                                    <option value="Technology">Technology</option>
                                    <option value="Vehicles">Vehicles</option>
                                    <option value="Services">Services</option>
                                </select>
                                </label>
                            </li>
                            <br>
                            <li>
                                <label id="labels"for="description" class="input-group">
                                <span>Describe your product in few words</span>
                                </label>
                                <textarea style="content-align:center;"name="description" cols="72" rows="4" placeholder=" Description"></textarea>
                            </li>
                            
                            <li>
                                <label id="labels" for="image" class="input-group">
                                <span class="input-group">Upload images of your product</span>
                                </label>
                                <input  lang="en" id="inputFile" class="input-group" type="file" accept="image/*" name="file[]" runat="server" multiple="multiple" placeholder=" Image" onchange="readURL(this);" multiple/>
                                <div id="preview"></div>
                            </li>
                            <br>
                            <li id="botaosell" >
                                <button type="submit"  class="button is-block is-info is-large is-centered">Advertise</button>
                            </li>
                            <br>
                        </ul>
                  <div></div>                            
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Website/templates/edit.html
{% extends "base.html"%} {% block title %}Edit Profile{% endblock %}
{% block content %}
<div id="body1" class="mainContainer" style="heigth:auto;">
  <div class="hero is-sucess d-flex align-items-center justify-content-center">
      <tr>
         <td>
            <br>                                     
            <div  class="row content d-flex align-items-center justify-content-center" style="height:auto;">
            <div class="box" id="caixaindexpage">
            {% with messages = get_flashed_messages(with_categories=true) %} 
                {% if messages %} 
                    {% for category, message in messages %} 
                        {% if category =='error' %}
                            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                            {{ message }}
                            <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times;</span>
                            </button>
                            </div>
            {% endif %}{% endfor %}{%endif %}{% endwith %}    
            <form method="POST" action="/BuyOrSell/edit"  enctype="multipart/form-data" style="margin-right:2cm;">
               <ul id="formLabels" style="list-style: none;">
                  <h3 id="title">Edit your profile</h3>                  
                  <li>
                     <p style="tabe-size:4; justify-content:left !important;">&emsp;&emsp;Here you can indicate information about you.Fill in all fields so other users can accurately understand whtat is your bunisess area. Also leave your contacts. Try to incorporate a short description.</p>
                     <p>This elements are not required!</p>
                  </li> 
                    <br>                 
                  <li>
                     <label id="labels"for="name" class="input-group">
                     <span>Name:</span>
                     </label>                    
                     <input value="{{user.name}}" class="input-group" type="text" name="name" style="width:29.1%"placeholder=" Name">
                  </li>
                    <br>
                  <li>
                  <label id="labels"for="password" class="input-group" >
                     <span>Current password:</span>
                     <input  class="input-group" type="password" name="password1" id="password1" placeholder=" Current password">
                  </label>
                  </li>
                  <li>
                     <label id="labels"for="password" class="input-group" >
                        <span>New password:</span>
                        <input class="input-group-prepend" type="password"id="password2" name="password2" placeholder=" New password">
                     </label>
                  </li>
                  <li>
                     <label id="labels"for="password" class="input-group" >
                        <span>Confirm new password:</span>
                        <input class="input-group-prepend" type="password" id="password3" name="password3" placeholder=" Condirm the new password">
                     </label>
                  </li>
                  <li>
                     <label id="labels"for="email" class="input-group">
                     <span>Email:</span>&nbsp;&nbsp;&nbsp;
                     <input value="{{user.email}}" width="50px" type="text" name="email" class="input-group" id="email" placeholder=" Email">
                     </label>
                  </li>             
                  <br>
                  <li>
                     <label id="labels"for="description" class="input-group">
                     <span>Describe your business area or enterprise:</span>
                     </label>
                     {%if user.description!=''%}
                        <textarea style="content-align:center;"name="description" value="" cols="72" rows="4" >{{user.description}}</textarea>
                     {%else %}
                        <textarea style="content-align:center;"name="description" value=""cols="72" rows="4" placeholder=" Description"></textarea>
                     {%endif%}
                  </li>
                   <li>
                     <label id="labels" for="image" class="input-group">
                     <span class="input-group">Upload a picture for your profile:</span>
                     </label>
                     <input id="inputFile" class="input-group" type="file" accept="image/*" name="picProfile" runat="server" placeholder=" User picture"onchange="readURL(this,'#preview_pic');" />
                        <div id="preview_pic"></div>
                  </li>
                  <br>
                  <li>
                     <label id="labels" for="image" class="input-group">
                     <span class="input-group">Upload a picture of your logo and/or enterprise:</span>
                     </label>
                     <input  lang="en" id="inputFile" class="input-group" type="file" accept="image/*" name="logoPic" runat="server" placeholder=" Logo picture"onchange="readURL(this,'#preview_logo');" />
                     <div id="preview_logo"></div>
                  </li>                     
                     <br>
                  <li >
                     <form enctype="multipart/form-data" class="form-inline align-items-center justify-content-center" method="POST" action="/BuyOrSell/edit/">
                        <input id="del_account" type="hidden" name="del" value="0">
                        <button id="botaoedit" type="submit" style="width:5cm; float:left;"class="btn btn-outline-success">Save Changes</button> 
                    </form>
                     <button type="button" id="botaocancel" onclick="window.location.href='{{ url_for( ('views.profile'),id=user.id)}}';"style="width:5cm; color:red; float:right;"class="btn btn-outline-secondary">Cancel</button>                     
                  </li>
                  <br>            
               </ul>              
            </form>
            <br>            
         </div>          
      </div>
         <td>
      <tr>
   </div>
</div>
{%endblock%}

Website/templates/favorites.html
{% extends "base.html"%} {% block title %}Favorites{% endblock %}
{% block content %}
<div class="mainContainer" id="body1">
<br>
<h1 style="text-align:center; font-size:0.8cm;color:black; font-weight:bold">Your favorite products!!!</h1>
   <div class="hero is-sucess d-flex align-items-center justify-content-center">
      <tr>
         <td>
            <br>                                     
            <div  class="row content d-flex align-items-center justify-content-center" style="height:auto;">
            <div class="box" id="caixaindexpage">
         {% if produtos%}                
         {%for product in produtos%}          
         <div class="thumb-block  with-uploader tbm-init-ok" onclick="window.location.href='{{ url_for( ('views.products'), id=product.id) }}';"style="pading:3px; text-align:left;padding-inline-start:0em;padding-inline-end: 0em; justify-content:right;">
            <ul style="list-style: none;">
               <img class="article-img" src="{{ url_for('static', filename='/uploads/'+ product.picture[0].name +'/')}}" alt={{product.picture[0].name }} width="700px" height="300px" />
               <li style="font-size:20px;font-weight: bold;">{{ product.name }}</li>
               <li style="font-size:15px;">{{ product.type}}</li>
               <li style="font-size:16.5px;font-weight: bold;"><span style="font-size:12px;">{{ product.date.strftime('%Y-%m-%d') }}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{product.money }}€</li>
               {%if product.type =='Auctions' %}
              <li>
                  <p>Event date: {{ product.auctiondate.strftime('%m/%d/%Y, %H:%M') }}</p></li>
               {% endif %} 
               <li class="bullet-item">
                  <p style="font-size:12px;">Author:&nbsp;<a style="color:black;" href="{{url_for(('views.profile'),id=product.userOwnersid)}}">{{product.userOwners}}</a></p>
               </li>
            </ul>
         </div>
         {%endfor%}                                                 
         {%else%}
         <div  class="row content d-flex align-items-center justify-content-center" style="height:auto;">
            <h1 style="text-align:center; font-size:1cm; color:black; font-weight:bold">
            You haven't saved anything yet.</h1>
            <br>                
         </div>
         {%endif%}
      </div>
   </div>
</div>
{% endblock %}

Website/templates/forbiden.html
{% block forbiden %}
<div name="forbiden" class="row content d-flex align-items-center justify-content-center" style="background-color: rgb(238, 246, 255);position: fixed;min-width: 100%; min-height: 100%;">
    <img  style=" top:50%;left: 50%; text-align: center;"src="{{ url_for('static', filename='/img/403.jpg')}}" alt="forbiden" />
</div>
{% endblock %}

Website/templates/login.html
{% extends "base.html"%} {% block title %}Login{% endblock %}
{% block content %}
<div id="body" class="hero-body is-primary" type=variable value=blue>
   <div  class="container has-text-centered">
      <div class="column is-4 is-offset-4">
         <div class="box" id="caixa">
            <h3 class="title">Login</h3>
            {% with messages = get_flashed_messages(with_categories=true) %} 
            {% if messages %} 
            {% for category, message in messages %} 
            {% if category =='error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
               {{ message }}
               <button type="button" class="close" data-dismiss="alert">
               <span aria-hidden="true">&times;</span>
               </button>
            </div>
            {% endif %}{% endfor %}{%endif %}{% endwith %}
            <form style="margin-left:18px; "method="POST" action="/BuyOrSell/login">
               <div id="labels"class="input-group">
                  <span  id="icon" class="input-group-prepend"><i class="fa fa-envelope-o fa-fw"></i></span>&nbsp;&nbsp;
                  <input class="input-group-prepend" type="email" name="email" placeholder=" Email">
               </div>
               <br> 
               <div id="labels" class="input-group">
                  <span id="icon" class="input-group-prepend"><i class="fa fa-key fa-fw"></i></span>&nbsp;&nbsp;
                  <input class="input-group-prepend" type="password" name="password" placeholder=" Password">
               </div>
               <br>          
               <div class="field">
                  <label class="checkbox">
                  <input type="checkbox">
                  Remember me
                  </label>
               </div>
               <button id="botaologin"  type="submit" class="button is-block is-info is-large is-centered">Login</button>
            </form>
         </div>
      </div>
   </div>
</div>
{% endblock %}

Website/templates/notifications.html
{% extends "base.html"%} {% block title %}Notifications{% endblock %}
{% block content %}
<div class="main-container" id="mainContainer">
<br><br><br>
<h1 style="text-align:center;">Happened activities  in your absence</h1>
   <div class="box"id="caixaprofilepage" style="pading:3px; text-align:left;padding-inline-start:5em;padding-inline-end:5em; margin-top:10px;padding-top:1em;">
      <br>
      <div  class="row content d-flex align-items-center justify-content-center" style="height:auto;">
         {% if produtos%}                
         {%for product in produtos%}          
         <div class="thumb-block  with-uploader tbm-init-ok" onclick="window.location.href='{{ url_for( ('views.products'), id=product.id) }}';"style="pading:3px; text-align:left;padding-inline-start:0em;padding-inline-end: 0em; justify-content:right;">
            <ul style="list-style: none;">
               <img class="article-img" src="{{ url_for('static', filename='/uploads/'+ product.picture[0].name +'/')}}" alt={{product.picture[0].name }} width="700px" height="300px" />
               <li style="font-size:20px;font-weight: bold;">{{ product.name }}</li>
               <li style="font-size:15px;">{{ product.type}}</li>
               <li style="font-size:16.5px;font-weight: bold;"><span style="font-size:12px;">{{ product.date.strftime('%Y-%m-%d') }}</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{product.money }}€</li>
               {%if product.type =='Auctions' %}
               <li>Event date: {{ product.auctiondate.strftime('%m/%d/%Y, %H:%M') }}</li>
               {% endif %} 
               <li class="bullet-item">
                  <p style="font-size:14px;">Author:&nbsp;{{product.userOwners}}</p>
               </li>
            </ul>
         </div>
         {%endfor%}                                                 
         {%else%}
         <div  class="row content d-flex align-items-center justify-content-center" style="height:auto;">
            <h1 style="text-align:center; font-size:1cm; color:black; font-weight:bold">
            You haven't saved anything yet.</p>                
         </div>
         {%endif%}
      </div>
   </div>
</div>
{%endblock%}